"""cascade delete on parent_image_id

Revision ID: 8bb7ce8fdadc
Revises: 2286c5a9a2aa
Create Date: 2026-09-13 13:06:28.180272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb7ce8fdadc'
down_revision: Union[str, Sequence[str], None] = '2286c5a9a2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('images_parent_image_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'images', ['parent_image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_parent_image_id_fkey'), 'images', 'images', ['parent_image_id'], ['id'])
    # ### end Alembic commands ###
